In [3]:
import numpy as np

In [4]:

temp=np.array([[[[11,8,6,12,7,9,8],[28,32,24,25,28,27,32]],        
                 [[7,10,10,-13,8,14,9],[26,31,25,21,28,30,22]],
                 [[9,6,13,8,6,6,13],[24,30,24,27,25,20,25]],
                 [[13,13,13,6,15,7,9],[29,20,24,23,21,24,29]]],
 
                [[[11,8,11,9,13,11,9],[24,24,24,31,20,23,32]],
                 [[13,7,10,15,13,7,10],[29,29,24,25,28,32,28]],
                 [[8,13,8,8,15,12,11],[30,27,28,21,27,31,25]],
                 [[13,12,15,13,11,7,6],[29,26,30,26,22,32,27]]],

                [[[5,3,4,5,3,3,21],[19,18,18,18,22,2,5]],
                 [[5,6,6,4,7,7,21],[20,18,19,20,20,7,2]],
                 [[7,6,5,7,7,5,19],[20,20,22,18,20,4,3]],
                 [[8,7,6,2,6,4,18],[20,19,22,18,19,4,7]]],
                
                [[[7,10,-10,11,11,11,22],[21,20,19,18,20,71,12]],
                 [[10,7,8,7,10,7,19],[21,22,21,18,20,7,8]],
                 [[10,10,12,7,7,7,21],[20,22,22,21,21,12,12]],
                 [[7,7,8,10,11,12,18],[21,22,21,18,18,10,7]]]])

In [3]:
temp.shape

(4, 4, 2, 7)

In [4]:
for i in range(4):
    print(temp,i,0)

[[[[ 11   8   6  12   7   9   8]
   [ 28  32  24  25  28  27  32]]

  [[  7  10  10 -13   8  14   9]
   [ 26  31  25  21  28  30  22]]

  [[  9   6  13   8   6   6  13]
   [ 24  30  24  27  25  20  25]]

  [[ 13  13  13   6  15   7   9]
   [ 29  20  24  23  21  24  29]]]


 [[[ 11   8  11   9  13  11   9]
   [ 24  24  24  31  20  23  32]]

  [[ 13   7  10  15  13   7  10]
   [ 29  29  24  25  28  32  28]]

  [[  8  13   8   8  15  12  11]
   [ 30  27  28  21  27  31  25]]

  [[ 13  12  15  13  11   7   6]
   [ 29  26  30  26  22  32  27]]]


 [[[  5   3   4   5   3   3  21]
   [ 19  18  18  18  22   2   5]]

  [[  5   6   6   4   7   7  21]
   [ 20  18  19  20  20   7   2]]

  [[  7   6   5   7   7   5  19]
   [ 20  20  22  18  20   4   3]]

  [[  8   7   6   2   6   4  18]
   [ 20  19  22  18  19   4   7]]]


 [[[  7  10 -10  11  11  11  22]
   [ 21  20  19  18  20  71  12]]

  [[ 10   7   8   7  10   7  19]
   [ 21  22  21  18  20   7   8]]

  [[ 10  10  12   7   7   7  21]
   [ 20  

In [5]:
temp[:,:,:,1]

array([[[ 8, 32],
        [10, 31],
        [ 6, 30],
        [13, 20]],

       [[ 8, 24],
        [ 7, 29],
        [13, 27],
        [12, 26]],

       [[ 3, 18],
        [ 6, 18],
        [ 6, 20],
        [ 7, 19]],

       [[10, 20],
        [ 7, 22],
        [10, 22],
        [ 7, 22]]])

In [6]:
Q:print only the maximum temperature for all the weekdays of dec and feb?

Object `feb` not found.


In [7]:
temp[1::2,:,1,0:5]

array([[[24, 24, 24, 31, 20],
        [29, 29, 24, 25, 28],
        [30, 27, 28, 21, 27],
        [29, 26, 30, 26, 22]],

       [[21, 20, 19, 18, 20],
        [21, 22, 21, 18, 20],
        [20, 22, 22, 21, 21],
        [21, 22, 21, 18, 18]]])

Q:print all the days along with the week number in november when the minimum temperature was less than 8 degrees.

In [8]:
a=temp[0,:,0,:]
np.extract(a<8,a)
for index, i in np.ndenumerate(np.extract(a<8,a)):
    print(index,i)

(0,) 6
(1,) 7
(2,) 7
(3,) -13
(4,) 6
(5,) 6
(6,) 6
(7,) 6
(8,) 7


In [9]:
a=temp[0,:,0,:]

In [10]:
b=np.where(a<8)
day={0:'mon',1:'tue',2:'wed',3:'thur',4:'fri',5:'sat',6:'sun'}

In [11]:
for i in range(len(b[0])):
    week={0:'week 1',1:'week 2',2:'week 3 ',3:'week 4'}

In [12]:
for i in range(len(b[0])):
    print(week[b[0][i]])
    print(day[b[1][i]])

week 1
wed
week 1
fri
week 2
mon
week 2
thur
week 3 
tue
week 3 
fri
week 3 
sat
week 4
thur
week 4
sat


In [13]:
c=temp[1:3,:,1,:]
print(c)

[[[24 24 24 31 20 23 32]
  [29 29 24 25 28 32 28]
  [30 27 28 21 27 31 25]
  [29 26 30 26 22 32 27]]

 [[19 18 18 18 22  2  5]
  [20 18 19 20 20  7  2]
  [20 20 22 18 20  4  3]
  [20 19 22 18 19  4  7]]]


In [14]:
np.where(c>20)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3,
        3, 3, 3, 3, 3, 0, 2, 3], dtype=int64),
 array([0, 1, 2, 3, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
        2, 3, 4, 5, 6, 4, 2, 2], dtype=int64))

In [15]:
print('week where days have temp grater than 20 are')
print('dec,jan')
for i in range(len(temp[0])):
    print(temp[0][i],"     ",temp[1][i])

week where days have temp grater than 20 are
dec,jan
[[11  8  6 12  7  9  8]
 [28 32 24 25 28 27 32]]       [[11  8 11  9 13 11  9]
 [24 24 24 31 20 23 32]]
[[  7  10  10 -13   8  14   9]
 [ 26  31  25  21  28  30  22]]       [[13  7 10 15 13  7 10]
 [29 29 24 25 28 32 28]]
[[ 9  6 13  8  6  6 13]
 [24 30 24 27 25 20 25]]       [[ 8 13  8  8 15 12 11]
 [30 27 28 21 27 31 25]]
[[13 13 13  6 15  7  9]
 [29 20 24 23 21 24 29]]       [[13 12 15 13 11  7  6]
 [29 26 30 26 22 32 27]]


In [16]:
mean=np.mean(temp[0])

In [17]:
mean

17.267857142857142

In [18]:
q1=np.percentile(temp[0],25)

In [19]:
q1

9.0

In [20]:
q3=np.percentile(temp[0],75)

In [21]:
q3

25.0

In [22]:
iqr=q3-q1

In [23]:
iqr

16.0

In [24]:
outlier_1=mean-1.5*iqr
outlier_2=mean+1.5*iqr
print(outlier_1)
print(outlier_2)

-6.732142857142858
41.26785714285714


In [25]:
x=np.where(temp[0]<outlier_1) #LOCATION IN RESULT
print(x)

(array([1], dtype=int64), array([0], dtype=int64), array([3], dtype=int64))


In [26]:
y=np.where(temp[0]>outlier_2)
print(y)

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))


In [27]:
temp[0][temp[0]<outlier_1]=np.mean(temp[0,:,0,:])
print(temp[0])
temp[0][temp[0]>outlier_2]=np.mean(temp[0,:,1,:])
print(temp[0])

[[[11  8  6 12  7  9  8]
  [28 32 24 25 28 27 32]]

 [[ 7 10 10  8  8 14  9]
  [26 31 25 21 28 30 22]]

 [[ 9  6 13  8  6  6 13]
  [24 30 24 27 25 20 25]]

 [[13 13 13  6 15  7  9]
  [29 20 24 23 21 24 29]]]
[[[11  8  6 12  7  9  8]
  [28 32 24 25 28 27 32]]

 [[ 7 10 10  8  8 14  9]
  [26 31 25 21 28 30 22]]

 [[ 9  6 13  8  6  6 13]
  [24 30 24 27 25 20 25]]

 [[13 13 13  6 15  7  9]
  [29 20 24 23 21 24 29]]]


In [28]:
np.average(temp[:,:,1,:])

21.848214285714285

In [29]:
min=temp[1,0,0,:]
print('week 1 minimum temp of dec',np.average(min))
print('week 2 minimum temp of dec',np.average(temp[1,1,0,:]))

week 1 minimum temp of dec 10.285714285714286
week 2 minimum temp of dec 10.714285714285714


In [30]:
print('week 3 minimum temp of dec',np.average(temp[1,2,0,:]))
print('week 4 minimum temp of dec',np.average(temp[1,3,0,:]))

week 3 minimum temp of dec 10.714285714285714
week 4 minimum temp of dec 11.0


In [31]:
np.average(temp[1:3,])

15.035714285714286

In [32]:
temp[1:3,:,0,:]
np.amin(temp[1:3,:,:,:])
k=np.min(temp[1:3,:,:,:])
m1={0:"nov",1:"dec",2:"jan",3:"feb"}
w1={0:"week(1)",1:"week(2)",2:"week(3)",3:"week(4)"}
d1={0:"monday",1:"tuesday",2:"wednesday",3:"thrusday",4:"friday",5:"saturday",6:"sunday"}
z=np.where(temp[1:3,:,:,:]==k)
for i in range(len(z[0])):
    print(m1[z[0][i]]," ",w1[z[1][i]]," ",d1[z[2][i]])

dec   week(1)   tuesday
dec   week(2)   tuesday
dec   week(4)   monday


In [5]:
a=temp[0,:,1,:]

In [6]:
a

array([[28, 32, 24, 25, 28, 27, 32],
       [26, 31, 25, 21, 28, 30, 22],
       [24, 30, 24, 27, 25, 20, 25],
       [29, 20, 24, 23, 21, 24, 29]])

In [7]:
y=np.average(temp[0])

In [8]:
np.where(y>a)   #all nov maximum value are not less then to average value

(array([], dtype=int64), array([], dtype=int64))

In [9]:
R=temp+32
print('fahrenheit array',R)

fahrenheit array [[[[ 43  40  38  44  39  41  40]
   [ 60  64  56  57  60  59  64]]

  [[ 39  42  42  19  40  46  41]
   [ 58  63  57  53  60  62  54]]

  [[ 41  38  45  40  38  38  45]
   [ 56  62  56  59  57  52  57]]

  [[ 45  45  45  38  47  39  41]
   [ 61  52  56  55  53  56  61]]]


 [[[ 43  40  43  41  45  43  41]
   [ 56  56  56  63  52  55  64]]

  [[ 45  39  42  47  45  39  42]
   [ 61  61  56  57  60  64  60]]

  [[ 40  45  40  40  47  44  43]
   [ 62  59  60  53  59  63  57]]

  [[ 45  44  47  45  43  39  38]
   [ 61  58  62  58  54  64  59]]]


 [[[ 37  35  36  37  35  35  53]
   [ 51  50  50  50  54  34  37]]

  [[ 37  38  38  36  39  39  53]
   [ 52  50  51  52  52  39  34]]

  [[ 39  38  37  39  39  37  51]
   [ 52  52  54  50  52  36  35]]

  [[ 40  39  38  34  38  36  50]
   [ 52  51  54  50  51  36  39]]]


 [[[ 39  42  22  43  43  43  54]
   [ 53  52  51  50  52 103  44]]

  [[ 42  39  40  39  42  39  51]
   [ 53  54  53  50  52  39  40]]

  [[ 42  42  44  39  39  

In [10]:
a=np.average(temp[1,0])
b=np.average(temp[1,1])
c=np.average(temp[1,2])
d=np.average(temp[1,3])
print(a)
print(b)
print(c)
print(d)

17.857142857142858
19.285714285714285
18.857142857142858
19.214285714285715


In [11]:
h=np.array([a,b,c,d])

In [12]:
h

array([17.85714286, 19.28571429, 18.85714286, 19.21428571])

In [13]:
np.sort(h)[::-1]

array([19.28571429, 19.21428571, 18.85714286, 17.85714286])

In [14]:
a==np.average(temp[0,:,:,0:3])
b=np.average(temp[1,:,:,0:3])
c=np.average(temp[2,:,:,0:3])
d=np.average(temp[3,:,:,0:3])
print(a)
print(b)
print(c)
print(d)


17.857142857142858
18.875
12.625
14.083333333333334


In [15]:
a=np.average(temp[0,:,:,0:3])
a

18.166666666666668

In [16]:
w=np.array([a,b,c,d])

In [17]:
w

array([18.16666667, 18.875     , 12.625     , 14.08333333])

In [18]:
np.sort(w)[::-1]

array([18.875     , 18.16666667, 14.08333333, 12.625     ])

In [19]:
x=temp[:,:,0,:]
y=temp[:,:,1,:]
diff=y-x
print(diff)

[[[ 17  24  18  13  21  18  24]
  [ 19  21  15  34  20  16  13]
  [ 15  24  11  19  19  14  12]
  [ 16   7  11  17   6  17  20]]

 [[ 13  16  13  22   7  12  23]
  [ 16  22  14  10  15  25  18]
  [ 22  14  20  13  12  19  14]
  [ 16  14  15  13  11  25  21]]

 [[ 14  15  14  13  19  -1 -16]
  [ 15  12  13  16  13   0 -19]
  [ 13  14  17  11  13  -1 -16]
  [ 12  12  16  16  13   0 -11]]

 [[ 14  10  29   7   9  60 -10]
  [ 11  15  13  11  10   0 -11]
  [ 10  12  10  14  14   5  -9]
  [ 14  15  13   8   7  -2 -11]]]


Q23 find and store tghe difference between the max temp of two consecutive days for each month of winter season

In [20]:
k=temp[:,:,1,:]
arr=np.diff(k,axis=2)
print(arr)

[[[  4  -8   1   3  -1   5]
  [  5  -6  -4   7   2  -8]
  [  6  -6   3  -2  -5   5]
  [ -9   4  -1  -2   3   5]]

 [[  0   0   7 -11   3   9]
  [  0  -5   1   3   4  -4]
  [ -3   1  -7   6   4  -6]
  [ -3   4  -4  -4  10  -5]]

 [[ -1   0   0   4 -20   3]
  [ -2   1   1   0 -13  -5]
  [  0   2  -4   2 -16  -1]
  [ -1   3  -4   1 -15   3]]

 [[ -1  -1  -1   2  51 -59]
  [  1  -1  -3   2 -13   1]
  [  2   0  -1   0  -9   0]
  [  1  -1  -3   0  -8  -3]]]


In [21]:
s=temp[:,:,0,:]
arr=np.diff(s,axis=2)
print(arr)

[[[ -3  -2   6  -5   2  -1]
  [  3   0 -23  21   6  -5]
  [ -3   7  -5  -2   0   7]
  [  0   0  -7   9  -8   2]]

 [[ -3   3  -2   4  -2  -2]
  [ -6   3   5  -2  -6   3]
  [  5  -5   0   7  -3  -1]
  [ -1   3  -2  -2  -4  -1]]

 [[ -2   1   1  -2   0  18]
  [  1   0  -2   3   0  14]
  [ -1  -1   2   0  -2  14]
  [ -1  -1  -4   4  -2  14]]

 [[  3 -20  21   0   0  11]
  [ -3   1  -1   3  -3  12]
  [  0   2  -5   0   0  14]
  [  0   1   2   1   1   6]]]


In [ ]:
add_array=np.concatenate([s,k])
add_array.fla